### PR TITLE
Fix 2FA issue

### PR DESCRIPTION
**Pull request by mzch**
Fix 2FA Issue

### CODE REVIEW

**Comment by MrXyfir** [comment]
Could you please test this with the Authy app and verify it still works? If I remember correctly there was an incompatibility with `otpauth_url` and Authy and that's why we generated our own URL. It's possible that Authy has fixed the issue by now though!

**Comment by mzch** [comment]
Yes, Authy, Google Authenticator, Step Two, OPT Auth, 1Password and Bitwarden all return the same TOTP code.
Perhaps Authy fixed such an issue.

**Comment by mzch** [comment]
`speakeasy::generateSecret` calls `otpauthURL` inside, so using `optauth_url` is no different than calling `otpauthURL` outside...?

**Comment by MrXyfir** [comment]
Yes but I believe the parameters we passed to `generateSecret` were different than what speakeasy used. But if it's working then no problem!

**Pull request merged**
